create database BOOK_MANAGE;
Use BOOK_MANAGE;
CREATE TABLE CATEGORY
(
ID INTEGER(15) NOT NULL auto_increment,
CATEGORY_NAME VARCHAR(30),
primary key(ID)
) 	;	

CREATE TABLE AUTHOR (
    ID INTEGER(15) NOT NULL auto_increment,

    AUTHOR_NAME VARCHAR(30),
    PRIMARY KEY (ID)
);
CREATE TABLE BOOK 
(
ID INTEGER(15) NOT NULL auto_increment,
BOOK_NAME VARCHAR(30),
AMOUNT INT(15),
CATEGORY_NAME VARCHAR(30),
AUTHOR_NAME VARCHAR(30),
primary key(ID)
);
ALTER TABLE BOOK ADD FOREIGN KEY(AUTHOR_NAME) REFERENCES AUTHOR(AUTHOR_NAME);
ALTER TABLE BOOK ADD FOREIGN KEY(CATEGORY_NAME) REFERENCES CATEGORY(CATEGORY_NAME);

Insert into AUTHOR (ID, AUTHOR_NAME) values ("1", "Tran Hoang Long");
Insert into CATEGORY(ID, CATEGORY_NAME) values("1", " Lich su");
Insert into BOOK(ID, BOOK_NAME, AMOUNT, CATEGORY_NAME, AUTHOR_NAME) values
 ("1","Lich su dai viet","30","Lich su","Tran Hoang Long");
