CREATE database BOOK_MANAGE;
Use BOOK_MANAGE;
CREATE TABLE CATEGORY
(
ID INTEGER(15) ,
CATEGORY_NAME VARCHAR(30),
primary key(CATEGORY_NAME)
) 	;	

CREATE TABLE AUTHOR (
    ID INTEGER(15) ,
    AUTHOR_NAME VARCHAR(30),
    PRIMARY KEY (AUTHOR_NAME)
);
CREATE TABLE BOOK 
(
ID INTEGER(15) NOT NULL auto_increment,
BOOK_NAME VARCHAR(30),
AMOUNT INT(15),
CATEGORY_NAME VARCHAR(30),
AUTHOR_NAME VARCHAR(30),
FIRST_LETTER VARCHAR(5),
primary key(ID)
);
Create table BOOK_LETTER_ORDINAL(
	ID Integer(30) ,
	LETTER varchar(5),
    PRIMARY KEY(LETTER)
 );
ALTER TABLE BOOK ADD FOREIGN KEY(FIRST_LETTER) REFERENCES BOOK_LETTER_ORDINAL (LETTER);
ALTER TABLE BOOK ADD FOREIGN KEY(AUTHOR_NAME) REFERENCES AUTHOR(AUTHOR_NAME);
ALTER TABLE BOOK ADD FOREIGN KEY(CATEGORY_NAME) REFERENCES CATEGORY(CATEGORY_NAME)