create database BOOK_MANAGE;
Use BOOK_MANAGE;
CREATE TABLE CATEGORY
(
ID INTEGER(15) NOT NULL auto_increment,
CATEGORY_NAME VARCHAR(30),
primary key(ID)
) 	;	

CREATE TABLE AUTHOR (
    ID INTEGER(15) NOT NULL auto_increment,
    AUTHOR_NAME VARCHAR(30),
    PRIMARY KEY (ID)
);
CREATE TABLE BOOK 
(
ID INTEGER(15) NOT NULL auto_increment,
BOOK_NAME VARCHAR(30),
AMOUNT INT(15),
CATEGORY_NAME VARCHAR(30),
AUTHOR_NAME VARCHAR(30),
primary key(ID)
);